### ISSUE TITLE
Join your team

### ISSUE THREAD

**Issue by saleem-hadad** [namshi/expressjs-utils#15]
Hello guys,
I came across your LinkedIn profile for a job application and I came here to see your work and understand your dev environment more.
Honestly, you're doing a great job and I like the team structure a lot and that's encouraged me to learn more about your organization.
Based on my experience as Co-Founder and Tech Leader at Binary Torch Sdn. Bhd. and MySenior, I believe I could be a good fit to join your team.
Recently I moved to Dubai to get married and that forced me to leave my old job in Malaysia.
I have ~5 years of experience in software development (specifically web and mobile development) and I have a solid background of development life cycle since I was leading the tech stack of the companies I work with.

Please let me know if you’d be open to a conversation to discuss this position. I’m happy to provide you with any additional information you might need. I look forward to hearing from you. Also, you can take a look at my Github profile to see my latest open-source projects :)

Best regards,

**Comment by odino** [comment]
Hi there, @saleem-hadad! :)

Would you mind sending your CV / profiles to `work-in-tech@namshi.com`? That's our way to get things started :) In case we have an opening that's suitable to your profile we'll get in touch and start the process.

Cheers!

**Comment by saleem-hadad** [comment]
Thank you @odino for your response.
Sure, I completely understand and will send my resume very soon to the mentioned email 🤓

Thanks for your time.
Cheers 💃
